import type { SupabaseClient } from "@supabase/supabase-js";
import type { Database } from "@/types/database";
import { retrieveStudentContext } from "./retrieval";
import { buildStudentContext } from "./context-builder";

// Retrieve Gemini API Key from environment (checks both casing variations)
function getApiKey(): string {
  const key = process.env.GEMINI_API_KEY || process.env.Gemini_API_KEY;
  if (!key) {
    // If not configured, fall back to safe placeholder or throw during active calls
    console.warn("GEMINI_API_KEY is not defined in environment variables.");
  }
  return key || "";
}

/**
 * Calls Gemini text-embedding-004 model to generate vector embeddings (768 dimensions).
 */
export async function getEmbedding(text: string): Promise<number[] | null> {
  const apiKey = getApiKey();
  if (!apiKey) return null;

  try {
    const response = await fetch(
      `https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:embedContent?key=${apiKey}`,
      {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          model: "models/text-embedding-004",
          content: {
            parts: [{ text }]
          }
        })
      }
    );

    if (!response.ok) {
      const errText = await response.text();
      throw new Error(`Embedding API returned status ${response.status}: ${errText}`);
    }

    const data = await response.json();
    return data.embedding?.values || null;
  } catch (error) {
    console.error("Gemini embedding failure:", error);
    return null;
  }
}

/**
 * Low-level text generator using Gemini 2.5 Flash/Pro models via REST.
 */
export async function generateGeminiContent(
  prompt: string,
  modelType: "flash" | "pro" = "flash",
  jsonMode = false,
  systemInstruction?: string
): Promise<string> {
  const apiKey = getApiKey();
  if (!apiKey) {
    return JSON.stringify({
      error: "Gemini API key is not configured. Please add GEMINI_API_KEY to your .env.local file.",
      simulated: true,
      message: "This is a simulated response because your API key is missing."
    });
  }

  const model = modelType === "pro" ? "gemini-2.5-pro" : "gemini-2.5-flash";
  const url = `https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent?key=${apiKey}`;

  const requestBody: any = {
    contents: [
      {
        parts: [{ text: prompt }]
      }
    ],
    generationConfig: {
      temperature: modelType === "pro" ? 0.2 : 0.7,
      maxOutputTokens: 2048
    }
  };

  if (systemInstruction) {
    requestBody.systemInstruction = {
      parts: [{ text: systemInstruction }]
    };
  }

  if (jsonMode) {
    requestBody.generationConfig.responseMimeType = "application/json";
  }

  try {
    const response = await fetch(url, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(requestBody)
    });

    if (!response.ok) {
      const errText = await response.text();
      throw new Error(`Gemini API returned status ${response.status}: ${errText}`);
    }

    const data = await response.json();
    const candidateText = data.candidates?.[0]?.content?.parts?.[0]?.text;
    if (!candidateText) {
      throw new Error("No response generated by Gemini model.");
    }

    return candidateText;
  } catch (error: any) {
    console.error("Gemini content generation failure:", error);
    throw error;
  }
}

/**
 * End-to-end RAG pipeline. Retrieves student data, formats context, and sends to Gemini.
 */
export async function queryRAG(
  supabase: SupabaseClient<Database>,
  userId: string,
  userPrompt: string,
  modelType: "flash" | "pro" = "flash",
  systemInstruction?: string
): Promise<string> {
  // 1. Retrieve full student context (including matching memories)
  const contextData = await retrieveStudentContext(supabase, userId, userPrompt);

  // 2. Format context into Markdown
  const markdownContext = buildStudentContext(contextData);

  // 3. Assemble the prompt (never send raw user prompts directly)
  const fullPrompt = `
You are the Cadence Academic Operating System AI Assistant.
Use the following structured student context to help answer the user's question.

=========================================
${markdownContext}
=========================================

User Query:
"${userPrompt}"

Response guidelines:
- If recommending changes to a study plan, explain WHY based on difficulty, capacity, or upcoming exams (Explainable AI).
- If concepts are requested, provide clear academic breakdowns.
- Reference the student's metrics (focus consistency, stronger/weaker subjects) to customize study recommendations.
`;

  return generateGeminiContent(fullPrompt, modelType, false, systemInstruction);
}
